name: cli_students
description: CLI estudantes, busca por alunos, por id , por todos, cursos, adiciona, atualiza e deleta alunos.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  dio: ^5.7.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
